[workspace]
resolver = "2"
members = ["cli", "lib"]

[workspace.package]
version = "2.1.1"
edition = "2021"
license = "Apache-2.0"
homepage = "https://steel.new"
documentation = "https://docs.rs/steel/latest/steel/"
repository = "https://github.com/regolith-labs/steel"
readme = "./README.md"
keywords = ["solana"]

[workspace.dependencies]
bytemuck = "1.14"
clap = { features = ["derive", "env"], version = "^4.5" }
clap_v3 = { version = "3", package = "clap" }
anyhow = "1"
colored = "2"
git2 = "0.19"
indicatif = "0.17"
num_enum = "0.7"
prettyplease = "0.2"
syn = { features = ["full"], version = "2" }
solana-clap-v3-utils = "=1.18"
solana-cli-config = "=1.18"
solana-program = "=1.18"
solana-sdk = "=1.18"
spl-token-2022 = { features = ["no-entrypoint"], version = "3" }
spl-associated-token-account = { features = [ "no-entrypoint" ], version = "3" }
thiserror = "2"
tokio = "1"
quote = "1"
