[workspace]
resolver = "2"
members = ["cli", "lib"]

[workspace.package]
version = "3.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://steel.new"
documentation = "https://docs.rs/steel/latest/steel/"
repository = "https://github.com/regolith-labs/steel"
readme = "./README.md"
keywords = ["solana"]

[workspace.dependencies]
anyhow = "1"
bytemuck = "1"
clap = { features = ["derive", "env"], version = "^4.5" }
clap_v3 = { version = "3", package = "clap" }
colored = "3"
git2 = "0.20"
indicatif = "0.17"
num_enum = "0.7"
paste = "1"
prettyplease = "0.2"
quote = "1"
syn = { features = ["full"], version = "2" }
solana-clap-v3-utils = "2.1"
solana-cli-config = "2.1"
solana-program = "2.1"
solana-sdk = "2.1"
spl-associated-token-account = "6"
spl-token-2022 = "7"
thiserror = "2"
tokio = "1"
