[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2024-12-19"
components = ["rustfmt", "cargo", "clippy", "rust-analyzer", "llvm-tools-preview", "rust-src"]
profile = "default"
